### ISSUE TITLE
Force megahit to use a certain number of cores and maybe upgrade the version?

### ISSUE THREAD

**Issue by bio-boris** [kbaseapps/kb_megahit#20]
Force megahit to use a certain number of cores and maybe upgrade the version? It looks like too much CPU is in use and the node stops responding..

http://www.metagenomics.wiki/tools/assembly/megahit
 -t/--num-cpu-threads  <int>  number of CPU threads, at least 2. 
                               Default: auto detect to use all CPU threads.

**Comment by jayrbolton** [comment]
Addressed by #21 and #22
